### ISSUE TITLE
Tracking Issue for `sector-lang`

### ISSUE THREAD

**Issue by akabinds** [akabinds/sectordb#3]
This is a tracking issue for the development of the scripting, interfacing, and query language for **SectorDB**.

# Tasks
- [ ] Design language and define formal grammar
- [ ] Complete parser 
- [ ] Complete compiler
	- [ ] Code generation and optimization
	- [ ] Static analysis
	- [ ] Type inference
	- [ ] Query planning and execution

# Unresolved Questions 
- LLVM or Cranelift backend/infrastructure?
